# Generated by Django 5.0.1 on 2025-10-27 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Hackerz", "0001_initial"),
        ("Hackerz_E_commerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="in_wishlists", to="Hackerz_E_commerce.product"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
