# Generated by Django 5.0.1 on 2025-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hackerz", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="two_factor_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
