# Generated by Django 5.0.1 on 2025-10-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hackerz_E_commerce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code promo"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Pourcentage"),
                            ("fixed", "Montant fixe"),
                        ],
                        default="percentage",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valeur de la réduction",
                    ),
                ),
                (
                    "min_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Achat minimum",
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        default=0,
                        help_text="0 = illimité",
                        verbose_name="Utilisations maximales",
                    ),
                ),
                (
                    "used_count",
                    models.IntegerField(
                        default=0, verbose_name="Nombre d'utilisations"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Valide à partir de")),
                ("valid_to", models.DateTimeField(verbose_name="Valide jusqu'à")),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Code promo",
                "verbose_name_plural": "Codes promo",
                "ordering": ["-created"],
            },
        ),
    ]
