# Generated by Django 5.0.1 on 2025-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hackerz_E_commerce", "0002_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/%Y/%m/%d/"
            ),
        ),
    ]
